name: Update remote server
on: [push]
jobs:

  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        GH_REF_NAME: ${{ env.GITHUB_REF_NAME }}
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: GH_REF_NAME
        script: |
          ${{ secrets.SSH_SCRIPT }} $GH_REF_NAME
